name: Run test

permissions:
  checks: write
  contents: read

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ADMOB_APP_ID: "ca-app-pub-3940256099942544~3347511713"
      AD_UNIT_ID: "ca-app-pub-3940256099942544/1033173712"

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Create local.properties
        run: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
          echo "ADMOB_APP_ID=$ADMOB_APP_ID" >> local.properties
          echo "AD_UNIT_ID=$AD_UNIT_ID" >> local.properties
          
      - name: Decode google-services.json
        env:
          FIREBASE_SECRET: ${{ secrets.FIREBASE_SECRET }}
        run: echo $FIREBASE_SECRET > ${GITHUB_WORKSPACE}/app/google-services.json

      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew

      - name: Run unit tests
        run: ./gradlew clean testDebug

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: '**/build/test-results/test*/TEST-*.xml'
