name: Run test

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ADMOB_APP_ID: "ca-app-pub-3940256099942544~3347511713"
      AD_UNIT_ID: "ca-app-pub-3940256099942544/1033173712"

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Create local.properties
        run: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
          echo "ADMOB_APP_ID=$ADMOB_APP_ID" >> local.properties
          echo "AD_UNIT_ID=$AD_UNIT_ID" >> local.properties

      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew

      - name: Run unit tests
        run: ./gradlew clean testDebug